from typing import Protocol
from app.schemas.market import MarketObservation


class MarketDataProvider(Protocol):
    async def get_stock(self, ticker: str) -> MarketObservation: ...
    async def get_stocks(self, tickers: list[str]) -> list[MarketObservation]: ...
    async def search(self, query: str) -> list[dict]: ...
