"""phase3 core schema

Revision ID: d3698e0a0a61
Revises: 
Create Date: 2026-09-04 19:16:21.900757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3698e0a0a61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('instrument_type', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_index('uq_instruments_isin', 'instruments', ['isin'], unique=True, postgresql_where=sa.text('isin IS NOT NULL'))
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('fundamental_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=30), nullable=False),
    sa.Column('period_type', sa.String(length=15), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('revenue_growth', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('eps', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('eps_growth', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('profit', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('profit_growth', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('roce', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('interest_coverage', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("period_type IN ('QUARTERLY','ANNUAL')", name='ck_fundamental_snapshot_period_type'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fundamental_snapshots_instrument_period_snapshot', 'fundamental_snapshots', ['instrument_id', 'period_type', 'snapshot_at'], unique=False)
    op.create_index('ix_fundamental_snapshots_instrument_snapshot', 'fundamental_snapshots', ['instrument_id', 'snapshot_at'], unique=False)
    op.create_table('market_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('importance', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.CheckConstraint("event_type IN ('PRICE_MOVE','VOLUME_SURGE','52W_HIGH','52W_LOW','RELATIVE_OUTPERFORMANCE','FUNDAMENTAL_CHANGE','CORPORATE_ACTION','EARNINGS','OTHER')", name='ck_market_event_type'),
    sa.CheckConstraint("importance IN ('HIGH','MEDIUM','LOW')", name='ck_market_event_importance'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_events_instrument_importance_ts', 'market_events', ['instrument_id', 'importance', 'timestamp'], unique=False)
    op.create_index('ix_market_events_instrument_ts', 'market_events', ['instrument_id', 'timestamp'], unique=False)
    op.create_table('market_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('high_price >= low_price AND open_price BETWEEN low_price AND high_price AND close_price BETWEEN low_price AND high_price', name='ck_market_history_ohlc_consistency'),
    sa.CheckConstraint('open_price > 0 AND high_price > 0 AND low_price > 0 AND close_price > 0', name='ck_market_history_prices_positive'),
    sa.CheckConstraint('volume >= 0', name='ck_market_history_volume_nonneg'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_history_instrument_ts', 'market_history', ['instrument_id', 'timestamp'], unique=False)
    op.create_table('market_state',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('previous_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('market_cap', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ingestion_version', sa.BigInteger(), nullable=False),
    sa.Column('data_quality', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.CheckConstraint("data_quality IN ('FRESH','STALE','UNAVAILABLE')", name='ck_market_state_data_quality'),
    sa.CheckConstraint('previous_close IS NULL OR previous_close >= 0', name='ck_market_state_prev_close_nonneg'),
    sa.CheckConstraint('price > 0', name='ck_market_state_price_positive'),
    sa.CheckConstraint('volume >= 0', name='ck_market_state_volume_nonneg'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('instrument_id')
    )
    op.create_table('valuation_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('pe_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ev_ebitda', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('price_to_sales', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('fcf_yield', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('fcf_yield_basis', sa.String(length=20), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("fcf_yield_basis IS NULL OR fcf_yield_basis IN ('TTM_QUARTERLY','ANNUAL')", name='ck_valuation_snapshot_fcf_basis_enum'),
    sa.CheckConstraint('(fcf_yield IS NULL) OR (fcf_yield_basis IS NOT NULL)', name='ck_valuation_snapshot_fcf_basis_required'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_valuation_snapshots_instrument_observed', 'valuation_snapshots', ['instrument_id', 'observed_at'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('objective', sa.String(length=20), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("objective IN ('GROWTH','VALUE','STABILITY')", name='ck_watchlist_objective'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watchlists_user_id', 'watchlists', ['user_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('watchlist_id', 'instrument_id')
    )
    op.create_index('ix_watchlist_items_instrument_id', 'watchlist_items', ['instrument_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_watchlist_items_instrument_id', table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index('ix_watchlists_user_id', table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index('ix_valuation_snapshots_instrument_observed', table_name='valuation_snapshots')
    op.drop_table('valuation_snapshots')
    op.drop_table('market_state')
    op.drop_index('ix_market_history_instrument_ts', table_name='market_history')
    op.drop_table('market_history')
    op.drop_index('ix_market_events_instrument_ts', table_name='market_events')
    op.drop_index('ix_market_events_instrument_importance_ts', table_name='market_events')
    op.drop_table('market_events')
    op.drop_index('ix_fundamental_snapshots_instrument_snapshot', table_name='fundamental_snapshots')
    op.drop_index('ix_fundamental_snapshots_instrument_period_snapshot', table_name='fundamental_snapshots')
    op.drop_table('fundamental_snapshots')
    op.drop_table('users')
    op.drop_index('uq_instruments_isin', table_name='instruments', postgresql_where=sa.text('isin IS NOT NULL'))
    op.drop_table('instruments')
    # ### end Alembic commands ###
